### ISSUE TITLE
Every prediction fails on Replicate

### ISSUE THREAD

**Issue by cristianvogel** [Dabble-Studio/3d-to-photo#1] opened 2023-10-19 09:12 UTC
...for me. 

I have the setup and env config working correctly, but every attempt fails at the https://replicate.com/andreasjansson/stable-diffusion-inpainting checkpoint

**Comment by nmathew87** [comment] 2023-10-19 19:43
Could you share the error log? Just some checks
- did you run the image proc server
- can you see the prediction started on replicate?

**Comment by nmathew87** [comment] 2023-10-20 16:21
the issue seems to have been a replicate issue and has resolved itself. Could you confirm and i'll close the issue.

**Comment by nmathew87** [comment] 2023-10-20 16:22
closing for now as it seems a duplicate of this. But can reopen if issue persists
https://github.com/Dabble-Studio/3d-to-photo/issues/2

**Closed by nmathew87** 2023-10-20 16:22 UTC
